services:
  frontend:
    environment:
      - APPLICATION_NAME=bit-tracker-frontend
      - SECRET=c6b20183-be1e-4020-9c0a-85bef1cc5b8a
    build:
      context: ./frontend
    container_name: bit-tracker-frontend
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - backend

  backend:
    environment:
      - APPLICATION_NAME=bit-tracker-backend
      - SECRET=c6b20183-be1e-4020-9c0a-85bef1cc5b8a
    build:
      context: ./backend
    container_name: bit-tracker-backend
    ports:
      - 3001:3001
    restart: always 