services:
  nuxt-dockerize-example-ssr:
    environment:
      - APPLICATION_NAME=nuxt-dockerize-example-ssr
      - SECRET=c6b20183-be1e-4020-9c0a-85bef1cc5b8a
    build:
      context: .
      dockerfile: Dockerfile.ssr
    container_name: nuxt-dockerize-example-ssr
    ports:
      - 3000:3000
    restart: always
  nuxt-dockerize-example-ssg:
    build:
      context: .
      dockerfile: Dockerfile.ssg
    container_name: nuxt-dockerize-example-ssg
    ports:
      - 3001:3000
    restart: always